docs: add programming practices entry
Show-your-Heart/ShowYourHeart-docs pull request #3
Opened 2024-10-28 19:11 UTC by LuisHPorras

2024-10-29 08:19 UTC, perepicornell requested changes

2024-10-29 08:19 UTC, perepicornell commented on app/programming-practices.md
> +This branch contains the code devployed in production, its a stable branch and contains all the releases.
```suggestion
This branch contains the code deployed in production, it's a stable branch and contains all the releases.
```

2024-10-29 09:09 UTC, perepicornell requested changes

2024-10-29 09:09 UTC, perepicornell commented on app/programming-practices.md
> +On top of the fork based workflow we encourage the use of [Conventional Commits specification](https://www.conventionalcommits.org/es/v1.0.0/#especificaci%c3%b3n). We also use[Semantic Versioning](ht
```suggestion
On top of the fork based workflow we encourage the use of [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#specification). We also use[Semantic Versioning](https://semver.org/) for our releases.
```
Links pointing to the english versions.

2024-10-30 07:26 UTC, perepicornell commented
Luís I did a couple of tiny contributions to this PR but now I don't think I'm supposed to be the one approving the PR. At the beginning Coopdevs said they had some ideas about how to organize the repo for it to be an open source project so I think it's better that @sseerrggii takes a look.

2024-10-30 08:19 UTC, sseerrggii approved these changes
Thanks @LuisHPorras 

For me it's OK, @LuisHPorras could you review contributions in order to follow these guidelines?

2025-04-16 12:02 UTC, merged